[build-system]
requires = ["setuptools", "build", "twine", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dbt_workload"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "version.py"
fallback_version = "0.1.0"